{
 "title": "Windows Hyper-V VM and replication 20250715",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(windows_physical_disk_health_status,__tenant_id__)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_physical_disk_health_status,instance)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(windows_hyperv_vm_status,host)"
    }
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(windows_hyperv_vm_status,vm)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hyper-V VM Availability",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "windows_hyperv_vm_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\",host=~\"(?i:($host))\"}",
     "legendFormat": "{{ host }}\\{{ vm }}"
    }
   ]
  },
  {
   "title": "VM Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_hyperv_vm_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\",host=~\"(?i:($host))\"}",
     "legendFormat": "{{ host }}\\{{ vm }}"
    }
   ]
  },
  {
   "title": "VM Operational Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_hyperv_vm_state{__tenant_id__=~\"$tenant\",instance=~\"$instance\",host=~\"(?i:($host))\"}",
     "legendFormat": "{{ host }}\\{{ vm }}"
    }
   ]
  },
  {
   "title": "VM Replication Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_hyperv_replication_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\",source=~\"(?i:($host))\"}",
     "legendFormat": "{{ source }} > {{ destination }}\\{{ vm }}"
    }
   ]
  },
  {
   "title": "VM Replication Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_hyperv_replication_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\",source=~\"(?i:($host))\",vm=~\"$vm\"}",
     "legendFormat": "{{ source }} > {{ destination }}\\{{ vm }}"
    }
   ]
  }
 ]
}