{
 "title": "Windows Storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(windows_physical_disk_health_status,__tenant_id__)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_physical_disk_health_status,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Summary",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_physical_disk_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }} PDisk Health"
    },
    {
     "expr": "windows_physical_disk_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} PDisk Oper"
    },
    {
     "expr": "windows_storage_pool_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Pool Health"
    },
    {
     "expr": "windows_storage_pool_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Pool Oper"
    },
    {
     "expr": "windows_storage_pool_is_readonly{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Pool RO"
    },
    {
     "expr": "windows_virtual_disk_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Vdisk Health"
    },
    {
     "expr": "windows_virtual_disk_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Vdisk Oper"
    }
   ]
  },
  {
   "title": "Health Timeline",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "windows_physical_disk_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }} PDisk Health"
    },
    {
     "expr": "windows_physical_disk_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} PDisk Oper"
    },
    {
     "expr": "windows_storage_pool_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Pool Health"
    },
    {
     "expr": "windows_storage_pool_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Pool Oper"
    },
    {
     "expr": "windows_storage_pool_is_readonly{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Pool RO"
    },
    {
     "expr": "windows_virtual_disk_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Vdisk Health"
    },
    {
     "expr": "windows_virtual_disk_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{name}} Vdisk Oper"
    }
   ]
  },
  {
   "title": "Physical Disk Health Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_physical_disk_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Physical Disk Operational Status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_physical_disk_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Storage Pool Health status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_storage_pool_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Storage Pool Operational status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_storage_pool_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Virtual Disks Health status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_virtual_disk_health_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Virtual Disks Operational status",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_virtual_disk_operational_status{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}